spring:
  datasource:
    url: jdbc:mysql://localhost:23306/bunmo?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: bunmo_user
    password: bunmo_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: +911VYr4eRTnV4Ubb2i/GhmQjs9CCPnfVhxdXe/sX0l6rO4budtCOK4xCFUbspeiplwjZCotXsYsKGKi0DlIKw==
  access-token:
    expire-time: 86400000
  refresh-token:
    expire-time: 259200000

oauth2:
  kakao:
    client-id: kakao-client-id
    client-secret: kakao-secret
    redirect-uri: http://localhost:18080/api/v1/oauth2/kakao
    token-uri: https://kauth.kakao.com
    token-path: /oauth/token
    user-info-uri: https://kapi.kakao.com
    user-info-path: /v2/user/me