spring:
  application:
    name: bunmo
  datasource:
    url: jdbc:mysql://localhost:23306/lxp?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: bunmo_user
    password: bunmo_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 18080

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none

jwt:
  secret: +911VYr4eRTnV4Ubb2i/GhmQjs9CCPnfVhxdXe/sX0l6rO4budtCOK4xCFUbspeiplwjZCotXsYsKGKi0DlIKw==
  access-token:
    expire-time: 86400000
  refresh-token:
    expire-time: 259200000